//%attributes = {"lang":"en"}

var $cES_ZEN_DASHBOARD : cs:C1710.ZEN_DASHBOARDSelection
var $cE_ZEN_DASHBOARD : cs:C1710.ZEN_DASHBOARDEntity
var $c4DC_ZEN_DASHBOARD : 4D:C1709.DataClass
$c4DC_ZEN_DASHBOARD:=zen__ds["ZEN_DASHBOARD"]
$cES_ZEN_DASHBOARD:=$c4DC_ZEN_DASHBOARD.all()
//$cES_ZEN_DASHBOARD.drop()
$cE_ZEN_DASHBOARD:=$cES_ZEN_DASHBOARD.first()
If ($cE_ZEN_DASHBOARD#Null:C1517)
	$cE_ZEN_DASHBOARD.j_IOs:=Null:C1517
	zen_entity_save($cE_ZEN_DASHBOARD)
End if 
